###服务启动端口号
server:
  port: 8500

spring:
  application:
    name:  mall-pay
  redis:
    host: 106.12.77.33
    port: 6379
    password: 123456
    jedis:
      pool:
        max-idle: 100
        max-wait: 1
  ###数据库相关连接
  datasource:
    username: root
    password: ljj19951124
    url: jdbc:mysql://106.12.77.33:3306/mall_pay?useUnicode=true&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  ###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7070/eureka
####打印MyBatias日志
logging:
  level:
    ### 开发环境使用DEBUG 生产环境info或者error
    com.mayikt.member.mapper: DEBUG
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.fuhe.mall.pay.entity

feign:
  client:
    config:
      default:
        #设置feign的超时时间
        connectTimeout: 10000
        readTimeout: 10000


