spring:
  application:
    name: mall-weixin
server:
  port: 8200

#eureka注册中心地址
eureka:
    client:
        service-url:
            defaultZone: http://fuhe-mall.cn:7070/eureka
        #eureka本地刷新缓存的时间，本地默认为30S
        #registry-fetch-interval-seconds: 5

