#spring:
#  application:
#    name: mall-weixin
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://106.12.77.33:3306/mall_member?autoReconnect=true&useUnicode=true&characterEncoding=utf8
#    username: ENC(jK9V8Kqz0JPOrl5mpzIavA==)
#    password: ENC(SKsHRO51ZOdUosqPDLqBq+xqIkzfqiyP)
#    hikari:
#      readOnly: false
#      connectionTimeout: 60000
#      idleTimeout: 60000
#      validationTimeout: 3000
#      maxLifetime: 60000
#      loginTimeout: 5
#      maximumPoolSize: 60
#      minimumIdle: 10
#server:
#  port: 8200
#
##eureka注册中心地址
#eureka:
#    client:
#        service-url:
#            defaultZone: http://fuhe-mall.cn:7070/eureka
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/*Dao.xml
#jasypt:
#  encryptor:
#    password: EWRREWRERWECCCXC
#
#
#
#
