server:
  port: 7070
eureka:
  instance:
    hostname: fuhe-mall.cn
    ##服务过期时间配置,超过这个时间没有接收到心跳EurekaServer就会将这个实例剔除
    lease-expiration-duration-in-seconds: 15
    ##服务刷新时间配置，每隔这个时间会主动心跳一次
    lease-renewal-interval-in-seconds: 5
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false
  server:
    #关闭自我保护
    enable-self-preservation: true
    use-read-only-response-cache: false
    #清理间隔（单位毫秒，默认是60*1000）
    eviction-interval-timer-in-ms: 4000
    responseCacheAutoExpirationInSeconds: 150
